spec-version: 0.36.0

verbatim:
  cabal-version: 3.6

name:                hashi
version:             2.0
github:              "mpilgrem/hashi"
author:              "Mike Pilgrem"
maintainer:          "public@pilgrem.com"
license:             BSD-2-Clause-Views
copyright:           "Copyright 2013 Harald Bögeholz"

extra-source-files:
- LICENSE.md
- README.md

description: Solver for Hashiwokakero puzzles written in Haskell.

data-dir: resources

data-files:
- haskell-logo24x24.png

dependencies:
- base >= 4.7 && < 5
- JuicyPixels
- array
- colour
- containers
- diagrams-lib
- diagrams-lib
- diagrams-rasterific
- diagrams-svg
- gi-gdk
- gi-gdkpixbuf
- gi-gtk >= 4.0
- haskell-gi-base
- template-haskell
- text
- vector

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hashi-solve:
    main:                Main.hs
    source-dirs:         app
    generated-other-modules: Paths_hashi
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optl-mwindows
    - -optl=resources/haskell-logo.res
    dependencies:
    - hashi
